[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
dimensions = {columns = 150, lines = 45}
decorations = "None"
opacity = 0.75

[keyboard]
bindings = [
{key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
]

[font]
size = 14
