" vimrc file for vscode only

" highlight matched
set hlsearch
" case insensitive search
set ignorecase
set smartcase
" search while typing
set incsearch
" wrap-around when searching
set wrapscan
" show pressed keys in lower right corner
set showcmd
" tab -> spaces
set expandtab
set tabstop=2
set shiftwidth=2
" keep a 5 line buffer for the cursor from top/bottom of window
set scrolloff=5
" X11 clipboard
set clipboard=unnamedplus
" use ~ with movement
set tildeop

" mappings
inoremap jk <Esc>
inoremap kj <Esc>

nnoremap u :undo<CR>
nnoremap U :redo<CR>

nnoremap gd :vsc editor.action.revealDefinition<CR>
nnoremap gD :vsc editor.action.goToDeclaration<CR>
nnoremap grr :vsc editor.action.goToReferences<CR>
nnoremap gra :vsc editor.action.quickFix<CR>
nnoremap gri :vsc editor.action.goToImplementation<CR>
nnoremap grn :vsc editor.action.rename<CR>
nnoremap gc :vsc editor.action.commentLine<CR>
nnoremap gh :vsc clangd.switchheadersource<CR>

" builtin next and previous command 'cN' and 'cn'
nnoremap <Space>d :vsc workbench.actions.view.problems<CR>
nnoremap [d :vsc editor.action.marker.prev<CR>
nnoremap ]d :vsc editor.action.marker.next<CR>

nnoremap <S-K> :vsc editor.action.showHover<CR>

nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l

nnoremap <Space>w :w<CR>
nnoremap <Space>W :wa!<CR>
nnoremap <Space>q :q<CR>
nnoremap <Space>Q :qa!<CR>
nnoremap <Space>h :noh<CR>
nnoremap <Space>F :vsc workbench.action.showAllSymbols<CR>
nnoremap <Space>f :vsc workbench.action.quickOpen<CR>
nnoremap <Space>t :vsc workbench.action.focusAuxiliaryBar<CR>

nnoremap <Space>bd :bd<CR>
nnoremap <Space>bD :bd<CR>
nnoremap <Space>bv :vsc workbench.action.moveEditorToNextGroup<CR>
nnoremap <Space>bV :vsc workbench.action.moveEditorToPreviousGroup<CR>
nnoremap <S-L> :bn<CR>
nnoremap <S-H> :bp<CR>

" reselect visual block after indent
vnoremap < <gv
vnoremap > >gv
vnoremap F :vsc editor.action.formatSelection<CR>
vnoremap gc :vsc editor.action.commentLine<CR>
vnoremap p "_dP

" MOVE LINE/BLOCK
vnoremap <S-J> :m'>+<CR>gv
vnoremap <S-K> :m'<-2<CR>gv

